### ISSUE TITLE
Problem: Delete Album button on Facebook > View Content page deletes all albums

### ISSUE THREAD

**Issue by peterVG** [deplatformer/deplatformer-webapp#1]
This button should say "delete all albums". However, once a user has gone through the trouble of uploading all their Facebook albums to Deplatformer they probably then don't want to then turn around and delete them all. Alternatively there is a "Delete" option inside each Facebook album view. It is much more likely that the user may want to weed out one or two albums after the Deplatformer import. They can use this in-album delete button to achieve that goal. Therefore, it makes more sense to remove the "Delete Album" altogether from the Facebook > View content page.

Likewise, it should not appear on the "All media" page. Album deletion should just be done on an album-by-album basis.

**Comment by art-blocksec** [comment]
Will leave it for now, to be able to delete all facebook content if required
